import { useState } from 'react';
import { type Project, clone } from '../../shared/model';
import { APPROVED_FIELDS } from '../../shared/dictionary';
import { lookup } from '../../shared/expressions';
import { addCustomField, addMissingField, acceptMapping, changeField } from '../../shared/project';

export default function FieldMapping({project,onUpdate,onPreview}:{project:Project;onUpdate:(p:Project)=>void;onPreview:(id:string)=>void}) {
 const [selected,setSelected]=useState<string|null>(null),[adding,setAdding]=useState(false),[custom,setCustom]=useState(false),[name,setName]=useState('roomNumber'),[label,setLabel]=useState('Room No.'),[expression,setExpression]=useState(lookup('roomNumber')),[x,setX]=useState(.05),[y,setY]=useState(.15),[width,setWidth]=useState(.25),[height,setHeight]=useState(.025),[error,setError]=useState('');
 const m=project.fieldMappings.find(m=>m.id===selected);
 function edit(id:string){const m=project.fieldMappings.find(m=>m.id===id)!;const e=project.elements.find(e=>e.id===m.elementId);setSelected(id);setAdding(false);setCustom(false);setName(m.fieldName||'roomNumber');setExpression(e?.expression||m.expression||(m.fieldName?lookup(m.fieldName):''));setLabel(m.fieldLabel);setX(e?.x??.05);setY(e?.y??.15);setWidth(e?.width??.25);setHeight(e?.height??.025);setError('');}
 function apply(){try{if(x<0||y<0||width<=0||height<=0||x+width>1||y+height>1)throw Error('Position and size must fit within the normalized PDF page.');let q=clone(project);
  if(custom)q=addCustomField(q,name);if(adding||!m?.elementId){q=addMissingField(q,name,label,{x,y,width,height});if(m)q.fieldMappings=q.fieldMappings.filter(v=>v.id!==m.id);}
  else {q=changeField(q,m.id,name);const item=q.fieldMappings.find(v=>v.id===m.id)!;item.fieldLabel=label;item.expression=expression||lookup(name);const e=q.elements.find(e=>e.id===item.elementId)!;Object.assign(e,{x,y,width,height,expression:item.expression});q=acceptMapping(q,m.id);e.expression=item.expression;}
  onUpdate({...q,visualReviewed:false});setAdding(false);setSelected(null);setError('');
 }catch(e){setError((e as Error).message);}}
 return <div className="panel"><div className="panel-head"><h2>RDL field mapping & expressions</h2><div className="toolbar"><button onClick={()=>{setAdding(true);setCustom(false);setSelected(null);setLabel('Passport No.');setName('passportN');setExpression(lookup('passportN'));}}>+ Add field</button><button onClick={()=>{setAdding(true);setCustom(true);setSelected(null);setLabel('Custom label');setName('customField');setExpression(lookup('customField'));}}>+ Add custom field</button></div></div><p className="muted">Automatic mappings are already active. Use this editor only to correct a field, expression, label or position.</p><div className="table-scroll"><table className="expression-table"><thead><tr><th>PDF label</th><th>Detected value</th><th>System field</th><th>Source</th><th>Expression</th><th>Status</th><th>Actions</th></tr></thead><tbody>{project.fieldMappings.map(m=><tr key={m.id} className={selected===m.id?'selected-row':''}><td dir="auto">{m.detectedLabel}</td><td dir="auto">{m.detectedValue||'Blank / not detected'}</td><td>{m.fieldName||'Unmapped'}</td><td>{m.fieldName&&project.customFields.includes(m.fieldName)?'Custom':m.fieldName&&project.discoveredRdlFields.includes(m.fieldName)?'Detected RDL':'Automatic mapping'}</td><td><code>{m.expression||'No expression'}</code></td><td>{Math.round(m.confidence*100)}%<span className={`mapping-status ${m.status}`}>{m.fieldName?'auto-mapped':'requires review'}</span></td><td><div className="toolbar"><button onClick={()=>edit(m.id)}>Edit</button><button disabled={!m.elementId} onClick={()=>onPreview(m.elementId!)}>Position</button><button onClick={()=>{const q=clone(project);q.fieldMappings.find(v=>v.id===m.id)!.status='ignored';q.elements=q.elements.filter(e=>e.id!==m.elementId);q.visualReviewed=false;onUpdate(q);}}>Ignore</button><button onClick={()=>onUpdate({...project,fieldMappings:project.fieldMappings.filter(v=>v.id!==m.id),elements:project.elements.filter(e=>e.id!==m.elementId),visualReviewed:false})}>Remove</button></div></td></tr>)}</tbody></table></div>{!project.fieldMappings.length&&<p className="empty">Upload a PDF for automatic detection, or add a missing field.</p>}
 {(adding||m)&&<section className="field-inspector"><h3>{custom?'Add custom dynamic field':adding?'Add missing dynamic field':`Edit: ${m?.detectedLabel}`}</h3><div className="inspector-grid"><label className="form-label">System field{custom?<input value={name} onChange={e=>{setName(e.target.value);setExpression(lookup(e.target.value));}}/>:<select value={name} onChange={e=>{setName(e.target.value);setExpression(lookup(e.target.value));}}><optgroup label="Approved dictionary">{APPROVED_FIELDS.map(n=><option key={n}>{n}</option>)}</optgroup>{project.discoveredRdlFields.length>0&&<optgroup label="Detected from uploaded RDL">{project.discoveredRdlFields.filter(n=>!APPROVED_FIELDS.includes(n)).map(n=><option key={n}>{n}</option>)}</optgroup>}{project.customFields.length>0&&<optgroup label="Custom fields">{project.customFields.map(n=><option key={n}>{n}</option>)}</optgroup>}</select>}</label><label className="form-label">Source / visible label<input dir="auto" value={label} onChange={e=>setLabel(e.target.value)}/></label>{[['X',x,setX],['Y',y,setY],['Width',width,setWidth],['Height',height,setHeight]].map(([k,v,set])=><label className="form-label" key={String(k)}>{String(k)}<input type="number" step=".001" min="0" max="1" value={Number(v)} onChange={e=>(set as (v:number)=>void)(Number(e.target.value))}/></label>)}</div><label className="form-label">Advanced expression<textarea value={expression} onChange={e=>setExpression(e.target.value)} rows={3}/></label><p className="muted">Changing the system field regenerates the standard Lookup. Advanced edits are written into the actual RDL XML.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="toolbar"><button className="primary" onClick={apply}>Apply field</button><button onClick={()=>{setSelected(null);setAdding(false);setCustom(false);}}>Cancel</button></div></section>}
 </div>;
}
