import { useEffect, useState } from 'react';
import { clone, elementSchema, type Project, type Element } from '../../shared/model';
import { APPROVED_FIELDS } from '../../shared/dictionary';
import { lookup } from '../../shared/expressions';
export default function LayoutEditor({project,onUpdate,selectedId}:{project:Project;onUpdate:(p:Project)=>void;selectedId?:string|null}) {
 const [id,setId]=useState<string|null>(selectedId||null),[error,setError]=useState('');
 useEffect(()=>{if(selectedId)setId(selectedId);},[selectedId]);const selected=project.elements.find(e=>e.id===id);
 function update(key:string,value:unknown){if(!selected)return;const q=clone(project),e=q.elements.find(e=>e.id===id)!;const next=elementSchema.safeParse({...e,[key]:value});if(!next.success){setError(next.error.issues[0].message);return;}if(next.data.x+next.data.width>1||next.data.y+next.data.height>1){setError('Element extends beyond the source page.');return;}Object.assign(e,next.data);q.visualReviewed=false;setError('');if(key==='fieldName'){const m=q.fieldMappings.find(m=>m.elementId===id);if(m){m.fieldName=String(value);m.expression=lookup(String(value));m.status='requires_review';}}onUpdate(q);}
 return <section className="panel layout-editor"><div className="panel-head"><h2>Document element inspector</h2><button onClick={()=>{const e:Element={id:crypto.randomUUID(),kind:'text',text:'New static text',x:.05,y:.05,width:.3,height:.025,fontSize:9,bold:false,align:'Left'};onUpdate({...project,elements:[...project.elements,e],visualReviewed:false});setId(e.id);}}>Add static / geometric element</button></div><div className="designer-inspector"><div className="element-list" role="list">{project.elements.map(e=><button key={e.id} className={e.id===id?'active':''} onClick={()=>setId(e.id)}><small>{e.kind}</small><span>{e.kind==='dynamic'?e.fieldName:e.text||e.id}</span></button>)}</div><div>{selected?<><label className="form-label">Type<select value={selected.kind} onChange={e=>update('kind',e.target.value)}>{['text','dynamic','line','rectangle','image'].map(k=><option key={k}>{k}</option>)}</select></label>{selected.kind==='dynamic'?<><label className="form-label">Approved RDL field<select value={selected.fieldName||''} onChange={e=>update('fieldName',e.target.value)}><option value="">Select approved field</option>{APPROVED_FIELDS.map(n=><option key={n}>{n}</option>)}</select></label><code>{lookup(selected.fieldName||'')}</code></>:selected.kind==='text'?<label className="form-label">Exact static text<textarea dir="auto" value={selected.text||''} onChange={e=>update('text',e.target.value)}/></label>:null}
 <div className="inspector-grid">{(['x','y','width','height','fontSize'] as const).map(k=><label className="form-label" key={k}>{k}<input type="number" step={k==='fontSize'?.5:.001} value={selected[k]} onChange={e=>update(k,Number(e.target.value))}/></label>)}<label className="form-label">Font family<input value={selected.fontFamily||'Arial'} onChange={e=>update('fontFamily',e.target.value)}/></label><label className="form-label">Alignment<select value={selected.align} onChange={e=>update('align',e.target.value)}>{['Left','Center','Right'].map(a=><option key={a}>{a}</option>)}</select></label><label className="form-label">Border / line width (pt)<input type="number" min="0" max="10" step=".1" value={selected.lineWidth??.5} onChange={e=>update('lineWidth',Number(e.target.value))}/></label></div>
 <label className="consent"><input type="checkbox" checked={selected.bold} onChange={e=>update('bold',e.target.checked)}/> Bold</label><label className="consent"><input type="checkbox" checked={selected.italic||false} onChange={e=>update('italic',e.target.checked)}/> Italic</label>{selected.kind==='image'&&<><p className="muted">Only approve static property artwork. Never approve an uploaded guest-signature image.</p>{selected.imageData&&<img className="image-review" src={selected.imageData} alt="Candidate static artwork"/>}<label className="consent"><input type="checkbox" checked={selected.imageReviewed||false} disabled={!selected.imageData&&selected.id!=='property_logo'} onChange={e=>update('imageReviewed',e.target.checked)}/> Approved static artwork</label></>}
 {error&&<p className="error" role="alert">{error}</p>}<button onClick={()=>{onUpdate({...project,elements:project.elements.filter(e=>e.id!==id),fieldMappings:project.fieldMappings.filter(m=>m.elementId!==id),visualReviewed:false});setId(null);}}>Delete element</button><p className="muted">Changes regenerate actual downloadable RDL. X/Y/width/height are normalized 0–1 source-page coordinates.</p></>:<p className="empty">Select a detected element, use a field's Position action, or add an element.</p>}</div></div></section>;
}
