import { useState } from 'react';
import { type Project } from '../../shared/model';
import { effectiveElements } from '../../shared/project';
import { lookup } from '../../shared/expressions';
export default function RdlPreview({project,source,selectedId}:{project:Project;source:string|null;selectedId?:string|null}) {
 const [zoom,setZoom]=useState(.65),[mode,setMode]=useState('compare'),[debug,setDebug]=useState(false);
 const elements=effectiveElements(project);
 return <><div className="toolbar"><select aria-label="Comparison mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="original">Original PDF</option><option value="generated">Generated RDL model</option><option value="compare">Side by side</option><option value="overlay">Overlay</option></select><button onClick={()=>setZoom(Math.max(.25,zoom-.1))}>Zoom −</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(Math.min(1.5,zoom+.1))}>Zoom +</button><button onClick={()=>setZoom(.65)}>Fit</button>{[.75,1,1.25].map(z=><button key={z} onClick={()=>setZoom(z)}>{z*100}%</button>)}<label><input type="checkbox" checked={debug} onChange={e=>setDebug(e.target.checked)}/> Show field mapping</label></div><p className="muted">20 × 25 cm. PDF coordinates drive this model-only preview; Microsoft Report Builder rendering still requires independent verification. Mirror JSON never controls this layout.</p><div className="rdl-scroll"><div className={`rdl-comparison ${mode}`} style={{zoom}}>{['compare','original'].includes(mode)&&<div><p className="eyebrow">ORIGINAL PDF · SCALED TO DESIGN AREA</p>{source?<img className="original-page" src={source} alt="Uploaded registration card"/>:<div className="empty">Upload a PDF to compare.</div>}</div>}{mode!=='original'&&<div><p className="eyebrow">GENERATED RDL MODEL</p><div className="report-page">{mode==='overlay'&&source&&<img className="overlay-source" src={source} alt="Source overlay"/>}{project.logo&&<img className="report-logo" src={project.logo.dataUrl} alt="Approved property logo" style={(()=>{const e=elements.find(e=>e.id==='property_logo')||{x:.05,y:.02,width:.18,height:.08};return {left:`${e.x*100}%`,top:`${e.y*100}%`,width:`${e.width*100}%`,height:`${e.height*100}%`};})()}/>}
 {elements.map(e=>{const text=e.kind==='dynamic'?debug?lookup(e.fieldName||''):project.previewSampleData[e.fieldName||'']||`[${e.fieldName||'Unmapped'}]`:e.text;const vertical=e.kind==='line'&&e.width<.002;return <div className={`report-element ${e.kind} ${debug?'debug':''} ${e.id===selectedId?'selected-element':''}`} title={`${e.id}: ${e.kind==='dynamic'?lookup(e.fieldName||''):e.kind}`} key={e.id} style={{left:`${e.x*100}%`,top:`${e.y*100}%`,width:`${e.width*100}%`,height:`${e.height*100}%`,fontSize:`${e.fontSize}pt`,fontFamily:e.fontFamily||'Arial',fontWeight:e.bold?700:400,fontStyle:e.italic?'italic':'normal',textAlign:e.align.toLowerCase() as 'left'|'right'|'center',color:e.color||'#000000',background:e.kind==='rectangle'?e.background:undefined,borderStyle:e.kind==='rectangle'?(e.lineWidth===0?'none':'solid'):undefined,borderWidth:e.kind==='rectangle'?`${e.lineWidth??.5}pt`:undefined,borderColor:e.borderColor||'#000000',borderTop:e.kind==='line'&&!vertical?`${e.lineWidth??.5}pt solid ${e.borderColor||'#000000'}`:undefined,borderLeft:e.kind==='line'&&vertical?`${e.lineWidth??.5}pt solid ${e.borderColor||'#000000'}`:undefined,zIndex:['line','rectangle'].includes(e.kind)?1:e.kind==='image'?2:3}} dir="auto">{['text','dynamic'].includes(e.kind)?text:e.kind==='image'&&e.imageData?<><img src={e.imageData} alt={e.imageReviewed?'Approved artwork':'Unreviewed artwork'}/>{!e.imageReviewed&&<small className="image-warning">REVIEW IMAGE</small>}</>:null}</div>;})}</div></div>}</div></div></>;
}
