export const KIOSK_FIELDS = ['GuestTitle','FamilyName','GivenName','MiddleInitial','RoomNo','NoofGuest','AddressLine1','AddressLine2','ArrivalDate','DepartureDate','PostalCode','ReservationNo','DailyRate','CityState','Country','DepartureTime','EmailID','MembershipProgram','Nationality','PassportNo','DateOfBirth','Occupation','CompanyTravelAgent','VisitPurpose','PaymentMethod','CardNumber','CardExpiryDate','TermsAndCondition','SignatureImagePath','RoomType','RoomRate','ArrivalTime','Company','ExpiryDate','ReportName','HotelName','TotalAmount','RateCode','Mobile','ReservationNameID','Source','NoOfDays','ChildCount','ReservationType','CurrentTime'] as const;
export const DEFAULT_KIOSK_CHECKBOX_IMAGES={checked:'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAxElEQVR4nO2XTQ6EIAyFy4snYOcNvP9pvIE7roCZZEwmDpVSgWrC2xj84X1pa1NcjJEsBVN3egDA9Lvw89IlH2Fb3TMjcChsK7WQn5e/eyBjYQBQY6Xy3i0F/mt+BYHW5ty6KYBPmHG/NizNqwOUmosBcpXMSdJRITXPQZyfS9s5SjblILTmWYDURlKoKgA5CE3RqYowCCKhMRcDSDbXzhAoeZkzuTPAoPSDw+x87QZQ0/yjMRFNqbDcbS6vSoEbh1My1g7hykmSPrQVsAAAAABJRU5ErkJggg==',empty:'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAaUlEQVR4nO2XsQ3AIAwE31YmcMcG7D8NG9CxglNFihTa5K3or4OGE0dhLDPBxKmno4DAcV9E65/0WHNYzRu4WHPgDaL1x56DjEsASkDGJQAlIOMSgBKQcQlACSpOxbGZXn/7BkyfU5A5AWDgDZJ8KpIZAAAAAElFTkSuQmCC'};
const aliases:Record<string,string>={
 'guest name':'GivenName','first name':'GivenName','given name':'GivenName','last name':'FamilyName','family name':'FamilyName','room no':'RoomNo','room number':'RoomNo','arrival':'ArrivalDate','arrival date':'ArrivalDate','departure':'DepartureDate','departure date':'DepartureDate','reservation no':'ReservationNo','confirmation no':'ReservationNo','conf no':'ReservationNo','daily rate':'DailyRate','room rate':'RoomRate','address':'AddressLine1','address line 1':'AddressLine1','address line 2':'AddressLine2','postal code':'PostalCode','zip code':'PostalCode','city':'CityState','country':'Country','departure time':'DepartureTime','email':'EmailID','email id':'EmailID','nationality':'Nationality','passport no':'PassportNo','date of birth':'DateOfBirth','occupation':'Occupation','company':'Company','travel agent':'CompanyTravelAgent','purpose of stay':'VisitPurpose','purpose of visit':'VisitPurpose','payment method':'PaymentMethod','card number':'CardNumber','card expiry date':'CardExpiryDate','room type':'RoomType','arrival time':'ArrivalTime','mobile':'Mobile','no of guests':'NoofGuest','number of guests':'NoofGuest','child count':'ChildCount','signature':'SignatureImagePath','terms and condition':'TermsAndCondition'
};
const key=(s:string)=>s.toLowerCase().replace(/[.:]/g,'').replace(/\s+/g,' ').trim();
export const kioskFieldForLabel=(label:string)=>aliases[key(label)]||null;
export const kioskValueExpression=(name:string)=>`=First(Fields!${name}.Value, "DataSet1")`;
export const kioskCheckboxExpression=(index:number)=>`=IIf(\n  Lookup("RegCardConsent${index}Yes", Fields!ConsentCode.Value, Fields!ConsentValue.Value, "DataSet6") = "Yes",\n  "checkboxwithchecksign",\n  "checkboxempty"\n)`;
