import { DOMParser } from '@xmldom/xmldom';
import { validateXmlClosure } from './xml';
import { fields, type Project } from './model';
import { effectiveElements } from './project';
export const RDL_NS = 'http://schemas.microsoft.com/sqlserver/reporting/2016/01/reportdefinition';
export const PAGE_WIDTH = 19, PAGE_HEIGHT = 24;
export const escapeXml = (s: string) => s.replace(/[<>&"']/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;' }[c]!));
export const lookup = (name: string) => `=Lookup("${name}", Fields!FieldName.Value, Fields!FieldValue.Value, "DataSet1")`;
const inch = (n: number) => `${Math.max(0, n).toFixed(4)}in`;
export function generateRdl(p: Project): string { const es = effectiveElements(p), w = PAGE_WIDTH - 1, h = PAGE_HEIGHT - 1; const items = es.filter(e => e.kind !== 'image').map((e, i) => { const pos = `<Top>${inch(e.y * h)}</Top><Left>${inch(e.x * w)}</Left><Height>${inch(Math.min(e.height, 1 - e.y) * h)}</Height><Width>${inch(Math.min(e.width, 1 - e.x) * w)}</Width>`; if (e.kind === 'line')
    return `<Line Name="Line_${i}">${pos}<Style><Border><Color>#808080</Color><Style>Solid</Style><Width>0.5pt</Width></Border></Style></Line>`; if (e.kind === 'rectangle')
    return `<Rectangle Name="Rectangle_${i}"><ReportItems/>${pos}<Style><Border><Style>Solid</Style></Border></Style></Rectangle>`; const field = fields(p.regcardConfig).find(f => f.field_name === e.fieldName); const value = e.kind === 'dynamic' ? lookup(e.fieldName!) : (field?.field_label || e.text || ''); return `<Textbox Name="Textbox_${i}"><CanGrow>true</CanGrow><KeepTogether>true</KeepTogether><Paragraphs><Paragraph><TextRuns><TextRun><Value>${escapeXml(value)}</Value><Style><FontFamily>Arial</FontFamily><FontSize>${e.fontSize}pt</FontSize><FontWeight>${e.bold ? 'Bold' : 'Normal'}</FontWeight></Style></TextRun></TextRuns><Style><TextAlign>${e.align}</TextAlign></Style></Paragraph></Paragraphs>${pos}<Style><VerticalAlign>Top</VerticalAlign><PaddingLeft>0pt</PaddingLeft><PaddingRight>0pt</PaddingRight><PaddingTop>0pt</PaddingTop><PaddingBottom>0pt</PaddingBottom></Style></Textbox>`; }).join(''); const logoBounds=es.find(e=>e.kind==='image')||{x:.3/w,y:.15/h,width:2/w,height:1/h}; const image = p.logo ? `<Image Name="PropertyLogo"><Source>Embedded</Source><Value>PropertyLogo</Value><Sizing>FitProportional</Sizing><Top>${inch(logoBounds.y*h)}</Top><Left>${inch(logoBounds.x*w)}</Left><Height>${inch(logoBounds.height*h)}</Height><Width>${inch(logoBounds.width*w)}</Width><Style/></Image>` : ''; const embedded = p.logo ? `<EmbeddedImages><EmbeddedImage Name="PropertyLogo"><MIMEType>${escapeXml(p.logo.mime)}</MIMEType><ImageData>${p.logo.dataUrl.split(',')[1]}</ImageData></EmbeddedImage></EmbeddedImages>` : ''; return `<?xml version="1.0" encoding="utf-8"?><Report xmlns="${RDL_NS}" xmlns:rd="http://schemas.microsoft.com/SQLServer/reporting/reportdesigner"><AutoRefresh>0</AutoRefresh><DataSources><DataSource Name="ReportDataset"><ConnectionProperties><DataProvider>System.Data.DataSet</DataProvider><ConnectString>/* Local Connection */</ConnectString></ConnectionProperties><rd:SecurityType>None</rd:SecurityType></DataSource></DataSources><DataSets><DataSet Name="DataSet1"><Query><DataSourceName>ReportDataset</DataSourceName><CommandText>/* Local Query */</CommandText></Query><Fields><Field Name="FieldName"><DataField>FieldName</DataField><rd:TypeName>System.String</rd:TypeName></Field><Field Name="FieldValue"><DataField>FieldValue</DataField><rd:TypeName>System.String</rd:TypeName></Field></Fields></DataSet></DataSets><ReportSections><ReportSection><Body><ReportItems>${image}${items}</ReportItems><Height>23in</Height><Style/></Body><Width>18in</Width><Page><PageHeight>24in</PageHeight><PageWidth>19in</PageWidth><LeftMargin>0.5in</LeftMargin><RightMargin>0.5in</RightMargin><TopMargin>0.5in</TopMargin><BottomMargin>0.5in</BottomMargin><Style/></Page></ReportSection></ReportSections>${embedded}<Language>en-US</Language><ConsumeContainerWhitespace>true</ConsumeContainerWhitespace><rd:ReportUnitType>Inch</rd:ReportUnitType></Report>`; }
export type RdlValidation = {
    valid: boolean;
    expectedLookupCount: number;
    actualLookupCount: number;
    checks: {
        name: string;
        pass: boolean;
        detail: string;
    }[];
};
export function validateRdl(xml: string, p: Project): RdlValidation { const checks: RdlValidation['checks'] = [], errors: string[] = []; const check = (name: string, pass: boolean, detail = '') => checks.push({ name, pass, detail }); let doc: ReturnType<DOMParser['parseFromString']> | undefined; try {
    if (/<!DOCTYPE|<!ENTITY/i.test(xml))
        throw Error('DTD/entity declarations are forbidden.');
    doc = new DOMParser({ errorHandler: { warning: m => errors.push(m), error: m => errors.push(m), fatalError: m => errors.push(m) } }).parseFromString(xml, 'text/xml');
}
catch (e) {
    errors.push((e as Error).message);
} check('XML parses', !!doc && !errors.length, errors.join('; ')); const syntax = validateXmlClosure(xml); check('XML closure', syntax === null, syntax || ''); const root = doc?.documentElement; check('Report namespace', root?.localName === 'Report' && root.namespaceURI === RDL_NS); const text = (tag: string) => doc?.getElementsByTagName(tag)[0]?.textContent; check('Page dimensions', text('PageWidth') === '19in' && text('PageHeight') === '24in', '19 × 24 inches'); const datasets = Array.from(doc?.getElementsByTagName('DataSet') || []), ds = datasets.find(x => x.getAttribute('Name') === 'DataSet1'); check('DataSet1', !!ds); const names = Array.from(ds?.getElementsByTagName('Field') || []).map(x => x.getAttribute('Name')); check('Dataset fields', names.includes('FieldName') && names.includes('FieldValue')); const expected = effectiveElements(p).filter(e => e.kind === 'dynamic'), values = Array.from(doc?.getElementsByTagName('Value') || []).map(x => x.textContent || ''), actual = values.filter(v => v.startsWith('=Lookup')); check('Lookup count', expected.length === actual.length, `${actual.length} / ${expected.length}`); const allowed = new Set(fields(p.regcardConfig).map(f => f.field_name)); const used = new Map<string, number>(); for (const v of actual) {
    const m = /^=Lookup\("([A-Za-z_][A-Za-z0-9_]*)", Fields!FieldName\.Value, Fields!FieldValue\.Value, "DataSet1"\)$/.exec(v);
    if (m)
        used.set(m[1], (used.get(m[1]) || 0) + 1);
} check('Lookup syntax & system fields', actual.every(v => { const m = /^=Lookup\("([A-Za-z_][A-Za-z0-9_]*)", Fields!FieldName\.Value, Fields!FieldValue\.Value, "DataSet1"\)$/.exec(v); return !!m && allowed.has(m[1]); })); const expectedCounts = new Map<string, number>(); for (const e of expected)
    expectedCounts.set(e.fieldName!, (expectedCounts.get(e.fieldName!) || 0) + 1); check('Layout bounds', effectiveElements(p).every(e => e.x + e.width <= 1.00001 && e.y + e.height <= 1.00001 && e.x >= 0 && e.y >= 0)); check('Dynamic content exists', expected.length > 0); check('Every dynamic field', Array.from(expectedCounts).every(([name, n]) => used.get(name) === n)); check('No placeholder values', !values.some(v => /\{\{|^=Fields!|^=[A-Za-z_]+$/.test(v))); check('Logo', !p.logo || (!!doc?.getElementsByTagName('Image').length && !!doc?.getElementsByTagName('ImageData')[0]?.textContent)); return { valid: checks.every(c => c.pass), expectedLookupCount: expected.length, actualLookupCount: actual.length, checks }; }
